- .changeset/mighty-ladybugs-enjoy.md
- packages/sdk/README.md
- packages/sdk/src/VoucherifyClientSide.ts
- packages/sdk/src/VoucherifyServerSide.ts
Adding new option: `customHeaders` allowing developer to pass additional headers that should be send to Voucherify API with each request. This might prove to be useful when debugging different technical cases
> Allow to pass custom additional headers to requests made to Voucherify API

- .changeset/eleven-vans-swim.md
- packages/sdk/src/Promotions.ts
- packages/sdk/src/RequestController.ts
- packages/sdk/src/types/Promotions.ts
This Pull requests fixes following issues:
- `query params` passed to `this.client.post` method making POST request to Voucherify API were not stringified correctly
- `voucherify.promotions.validation` method was not accepting `query params` making it impossible to use advanced filters to restrict range of promotion campaigns against which validation should be performed - issue ref: https://github.com/voucherifyio/voucherify-js-sdk/issues/111
> [Improvement + BugFix] - Stringify query params passed to POST requests + allow to pass query params for promotion validation

- .changeset/sour-weeks-explode.md
- packages/sdk/README.md
- packages/sdk/src/Customers.ts
- packages/sdk/src/types/Customers.ts
Add support for calling: `v1/customers/{customer_ID}/activities` endpoint - https://docs.voucherify.io/reference/get-customer-activities
Closes https://github.com/voucherifyio/voucherify-js-sdk/issues/116
> [Improvement] Support for v1/customers/{customer_ID}/activities endpoint

- .changeset/hip-shirts-compare.md
- packages/sdk/src/types/DiscountVoucher.ts
- packages/sdk/src/types/Orders.ts
- packages/sdk/src/types/Validations.ts
There are few missing fields in the validate voucher response that the API returns but are not in the SDK type. 
Adding them here with this PR.
> [patch] Adding missing attributes in validate voucher response

- .changeset/bright-humans-type.md
- packages/sdk/src/types/Validations.ts
Missing `items_applied_discount_amount` and `total_applied_discount_amount`
> Add missing discount amounts on order type for validate voucher response

- .changeset/five-hotels-applaud.md
- packages/sdk/src/MetadataSchemas.ts
Add missing documentation links for:
- `MetaedaSchemas.list` method
- `MetadataSchemas.get` method
> [patch] Add missing documentation links for MetadataSchemas API methods

- .changeset/selfish-pears-wink.md
- packages/sdk/src/types/Redemptions.ts
https://github.com/voucherifyio/voucherify-js-sdk/issues/140
> [patch] Make customer's ID field optional when calling redeem method

- .changeset/tricky-rings-cry.md
- packages/sdk/src/types/Promotions.ts
https://github.com/voucherifyio/voucherify-js-sdk/issues/143
> [patch] Add missing 'name', 'start_date' and 'expiration_date' properties to PromotionsValidateResponse

- .changeset/chilled-buckets-flow.md
- packages/sdk/src/types/DiscountVoucher.ts
- packages/sdk/src/types/Promotions.ts
- packages/sdk/src/types/Validations.ts
Issues:
https://github.com/voucherifyio/voucherify-js-sdk/issues/146
https://github.com/voucherifyio/voucherify-js-sdk/issues/147
https://github.com/voucherifyio/voucherify-js-sdk/issues/148
- Drop `id` from `customer` in `promotions/validation` endpoint
- Add `applied_discount_amount` to `PromotionsValidateResponse` root type
- Add `hierarchy` to `PromotionsValidateResponse` root type
- Add `initial_amount` to `PromotionsValidateResponse` nested order type
- Add `items_discount_amount` to `PromotionsValidateResponse` nested order type
- Add `items_applied_discount_amount` to `PromotionsValidateResponse` nested order type
- Add `discount_amount` to `PromotionsValidateResponse` nested order type
- Add `total_discount_amount` to `PromotionsValidateResponse` nested order type
- Add …
> [patch] Fixes to request and response payload of promotions validation endpoint

- .changeset/curly-balloons-impress.md
- packages/sdk/src/types/Orders.ts
https://github.com/voucherifyio/voucherify-js-sdk/issues/151
**PATCH**
- Add `discount_quantity` property to `OrdersItem` interface
- Add `initial_quantity` property to `OrdersItem` interface
- Add `initial_amount` property to `OrdersItem` interface
- Add `subtotal_amount` property to `OrdersItem` interface
- Add `object` property to `OrdersItem` interface
- Add `metadata` property to `OrdersItem` interface
- Add `product.id` property to `OrdersItem` interface
- Add `product.source_id` property to `OrdersItem` interface
- Add `product.price` property to `OrdersItem` interface
- Add `sku.id` property to `OrdersItem` interface
- Add `sku.source_id` property to `OrdersItem` interface
- Add `sku.price` property to `OrdersItem` interface
> [patch] Add missing properties to OrdersItem interface

- .changeset/brown-birds-fly.md
- packages/sdk/src/types/Orders.ts
**PATCH**
- Add missing `total_amount` property to `OrdersCreateResponse` interface
> [patch] Add missing property to OrdersCreateResponse interface

- .changeset/tidy-apricots-allow.md
- packages/sdk/src/types/Campaigns.ts
- packages/sdk/src/types/ClientSide.ts
- packages/sdk/src/types/Loyalties.ts
- packages/sdk/src/types/Vouchers.ts
**PATCH**
- Add missing `created_at` property to `VouchersResponse`, `LoyaltiesRedeemRewardResponse`, `CampaignsAddVoucherResponse`, and `ClientSideVoucherListing` interfaces.
> [patch] Add missing property to `VouchersResponse` interface

- .changeset/cool-boxes-wait.md
- package.json
- packages/sdk/package.json
- yarn.lock
- Bumping `axios`, previous PR: https://github.com/voucherifyio/voucherify-js-sdk/pull/165 added new dependency to axios in root package.json instead of bumping `axios` in `packages/sdk`
> [patch] Bumping axios to 0.21.4

- .changeset/famous-donkeys-notice.md
- packages/sdk/package.json
- yarn.lock
- Bump qs dependency to 6.9.7 version to fix CVE-2022-24999 / GHSA-hrpp-h998-j3pp
> [patch] Bumping qs to 6.9.7 version to fix CVE-2022-24999 / GHSA-hrpp-h998-j3pp

- .changeset/twelve-cows-mate.md
- packages/sdk/src/types/Stackable.ts
- packages/sdk/src/types/ValidationError.ts
- packages/sdk/src/types/Validations.ts
https://github.com/voucherifyio/voucherify-js-sdk/issues/176
Patch
- New `ValidationError` typed interface
- Changed `error` property in `StackableRedeemableResultResponse` type from `any` to typed `ValidationError` type - it should not break anything since all returned fields should be present in `ValidationError` type
- Added new `error` property to `ValidationsValidateVoucherResponse` type
> [patch] Add new 'ValidationError' type describing error that can be returned upon unsuccessful validation 

- .changeset/green-readers-exist.md
- packages/sdk/src/types/Campaigns.ts
`assets` field is currently missing from the return type of `campaigns.addVoucher` method, which in reality the SDK returns the field.
> fix: add assets to issue voucher response type

- .changeset/twenty-dragons-reflect.md
- packages/sdk/src/VoucherifyError.ts
https://github.com/voucherifyio/voucherify-js-sdk/issues/187
Patch
- Add explicit fields: `related_object_ids`, `related_object_type`, `related_object_total`
> [patch] Add missing properties to VoucherifyError class

- .changeset/spicy-crews-fly.md
- packages/sdk/src/types/PromotionTiers.ts
- packages/sdk/src/types/Redemptions.ts
https://github.com/voucherifyio/voucherify-js-sdk/issues/193
https://github.com/voucherifyio/voucherify-js-sdk/issues/194
Patch
- Added `active` field to `PromotionTier`
- Added new `PromotionTierRedeemDetailsSimple` interface
- Added new `PromotionTierRedeemDetails` type
- Union of `PromotionTierRedeemDetailsSimple` and `PromotionTierRedeemDetails` can now be returned as part of new optional property `promotion_tier` of `RedemptionsRedeemResponse` interface - thanks to that now API Response from redeem stackable contains correct typing for `promotion_tier` in `redeemables`
> [patch] Add active field to PromotionTier and add promotion_tier property to possible redeemables

- .changeset/bright-goats-breathe.md
- packages/sdk/src/Campaigns.ts
https://github.com/voucherifyio/voucherify-js-sdk/issues/201
Minor
**Why minor?**
Some people might already added their own typing to `campaings.list` method due to lack of our own typing. Feels like making it `patch` would not be correct move, at the same time this is not breaking change since typing was never provided in first place. Unfortunately we overlooked this.
- Added typing to return value of `campaigns.list` SDK method
> [minor] Add typing to return value of campaigns.list method

- .changeset/old-spiders-begin.md
- packages/sdk/src/types/Orders.ts
- packages/sdk/src/types/PromotionTiers.ts
Currently the API supports only CANCELED and not CANCELLED. This PR fixes the SDK to send correct key
> Fixed typo in spellings of CANCELED

- .changeset/afraid-bees-fail.md
- packages/sdk/README.md
- packages/sdk/src/PromotionTiers.ts
- packages/sdk/src/types/PromotionTiers.ts
as the title says.
added support for [https://docs.voucherify.io/reference/get-promotion-tier](https://docs.voucherify.io/reference/get-promotion-tier)
> Added support for get promotion tier endpoint

- .changeset/fast-peaches-smash.md
- packages/sdk/src/types/Validations.ts
https://github.com/voucherifyio/voucherify-js-sdk/issues/213
Patch
- Added `metadata` property to `order` property in `ValidationsValidateVoucherResponse` interface
- Added `session` property to `ValidationsValidateVoucherResponse` interface
> [patch] Add missing properties to ValidationsValidateVoucherResponse interface

- .changeset/cool-eyes-learn.md
- packages/sdk/src/types/DiscountVoucher.ts
- packages/sdk/src/types/Distributions.ts
- packages/sdk/src/types/Stackable.ts
**PATCH**
- add `amount_off_formula`, `percent_off_formula`, `unit_off_formula`, and `fixed_amount_formula` fields to Voucher types: `DiscountAmount`, `DiscountPercent`, `DiscountUnit`, `DiscountFixed`, `VoucherDiscount`, and `StackableRedeemableResultDiscount`
> [patch] add missing '_formula' fields to Voucher types

- .changeset/modern-impalas-shake.md
- packages/sdk/README.md
- packages/sdk/src/RequestController.ts
- packages/sdk/src/VoucherifyClientSide.ts
- packages/sdk/src/VoucherifyServerSide.ts
Patch
- Added optional `timeoutMs` property to `VoucherifyServerSide` and `VoucherifyClientSide` classes allowing developers to set custom timeout in milliseconds after which Axios will abort the request. Fallback is set to `0` which means `No timeout`. In such case default timeout of 3 minutes is used which is what is set on Voucherify's Load Balancers
**Server Side Client:**
```
const client = VoucherifyServerSide({
applicationId: 'YOUR-APPLICATION-ID',
secretKey: 'YOUR-SECRET-KEY',
timeoutMs: 10000
})
```
**Client Side Client:**
```
const client = VoucherifyClientSide({
clientApplicationId: 'YOUR-APPLICATION-ID',
clientSecretKey: 'YOUR-CLIENT-SECRET-KEY',
timeoutMs: 10000
})
```
> [patch] Add option to pass timeout to VoucherifyServerSide client and VoucherifyClientSide client

- .changeset/tidy-king-sun.md
- packages/sdk/README.md
- packages/sdk/package.json
- packages/sdk/src/Exports.ts
- packages/sdk/src/types/Exports.ts
- packages/sdk/test/exports.spec.ts
---
'@voucherify/sdk': minor
---
Add support for endpoint `GET /exports`.
- New exported types/interfaces: `ExportsListRequestQuery`, `ExportsListResponseBody`, `ExportBase`, `ExportResourceResponse`, `FieldConditions`, `ExportVoucher`, `ExportVoucherFilters`, `ExportRedemption`, `ExportRedemptionFilters`, `ExportCustomer`, `ExportCustomerFilters`, `ExportPublication`, `ExportPublicationFilters`, `ExportOrder`, `ExportOrderFilters`, `ExportPointsExpiration`, `ExportPointsExpirationFilters`, `ExportVoucherTransactionsExpiration`, `ExportVoucherTransactionsFilters`, `Junction`, `FiltersCondition`, `ExportCustomerFields`, `ExportCustomerOrder`, `ExportPublicationFields`, `ExportPublicationOrder`, `ExportRedemptionFields`, `ExportRedemptionOrder`, `ExportVoucherFields`, `ExportVoucherOrder`, …
> Pz/types 005 - Exports

- .changeset/smooth-garlics-remain.md
- packages/sdk/src/VoucherifyError.ts
- packages/sdk/src/types/Vouchers.ts
- packages/sdk/test/redemptions.spec.ts
Changes:
- [Added error object in VoucherifyError.](https://github.com/voucherifyio/voucherify-js-sdk/commit/b7eec32edd87919713f218af93a7b6e4d1e3b5b1)
- [Added test Redemptions API with testing VoucherifyError](https://github.com/voucherifyio/voucherify-js-sdk/commit/49ea363d554d383da8b8a8e6db1babdca4d81709)
- [Added validation_rules to VouchersCreateParameters (mostly for test case). But can use in real case](https://github.com/voucherifyio/voucherify-js-sdk/commit/0144494d8c2a3607c834cfd660c5661d12c18325) (is valid with api https://docs.voucherify.io/reference/create-voucher)
> VoucherifyError update

- .changeset/hungry-roses-cross.md
- packages/sdk/README.md
- packages/sdk/src/Customers.ts
- packages/sdk/src/types/Customers.ts
- packages/sdk/test/customers.spec.ts
Patch
- Support for `customers/{id}/redeemables` endpoint - https://docs.voucherify.io/reference/list-customer-redeemables
> [patch] Add support for endpoint for  listing customer's redeemables

- .changeset/witty-files-sniff.md
- packages/sdk/src/types/Categories.ts
- packages/sdk/src/types/Redemptions.ts
- packages/sdk/src/types/Stackable.ts
- packages/sdk/src/types/Validations.ts
- packages/sdk/test/redemptions.spec.ts
Why?
Our SDK was outdated.
What was added:
- Support to new redeemables mode (PARTIAL): added `skipped_redeemables`, `inapplicable_redeemables`.
- Details result of `skipped_redeemables` and `inapplicable_redeemables` in main `StackableRedeemableResultResponse`
> additions to stacked validations and stacked redemptions

- .changeset/quick-chairs-breathe.md
- packages/sdk/README.md
- packages/sdk/src/Consents.ts
- packages/sdk/src/Customers.ts
- packages/sdk/src/types/Customers.ts
- packages/sdk/src/types/Validations.ts
- packages/sdk/test/customers.spec.ts
- Added support for `v1/customers/{customerId}/activity` (method `listActivity`)
- Fix type `ValidationValidateStackableResponse`
- Added test
> [Minor] customers.listActivity and fix type ValidationValidateStackableResponse - v2.8.0

- .changeset/seven-tools-drum.md
- packages/sdk/src/types/Loyalties.ts
- packages/sdk/src/types/Vouchers.ts
Added missing type properties in voucher.loyalty_card - for example for requesting voucher/loyalty member
Requested by a customer
> v2.9.1 - Added missing type properties in voucher.loyalty_card

- .changeset/beige-items-burn.md
- package-lock.json
- packages/sdk/package.json
- packages/sdk/src/RequestController.ts
- packages/sdk/src/types/Orders.ts
- packages/sdk/test/qualifications.spec.ts
- yarn.lock
Fixing `CVE-2025-27152`, however I think there is no danger here, because we provide relative paths everywhere, so end-customer can not enter absolute URLs.
- Upgrading axios
- Setting `allowAbsoluteUrls: false` just to be sure
- Fixing packages/sdk/test/qualifications.spec.ts -> seems like OrderCalculated does not need to have `metadata` (confirmed on 2 clusters)
> Upgrade axios

- .changeset/fair-tomatoes-relax.md
- package-lock.json
- packages/sdk/src/types/Balance.ts
- packages/sdk/test/vouchers.spec.ts
Added two missing parameters from `Add voucher balance` endpoint.
[Issue](https://github.com/voucherifyio/voucherify-js-sdk/issues/289)
> added missing params
